
name: dependency-review

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: 'dependency-review-${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Dependency review
        uses: actions/dependency-review-action@v4
